### ISSUE TITLE
ADC error no attribute 'read'`

### ISSUE THREAD

**Issue by oxicottin** [ashleywm/micropython-capacitive-soil-moisture-sensor#1]
Hello, I can not get this working on my Pico... I keep getting the error below in the Thonny shell. Ideas why?

Calibrated min/max values not set. Run calibration.
Calibrate sensor for the minimum environment, for example in air.
Calibration will start in 10 seconds.
Starting minimum calibration
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "CSMS.py", line 65, in calibrate
  File "CSMS.py", line 89, in read_raw
AttributeError: 'ADC' object has no attribute 'read'

**Comment by oxicottin** [comment]
its the line 

reading = self.adc.read()
